Repository amosproj/amos2024ss05-knowledge-graph-extractor, pull requests merged in 2024-05, with the labels that each got.

#38 Added a pull request template
  .github/workflows/pull_request_template.md
Labels: documentation

#46 Backend for uploading PDF Documents
  Project/backend/Makefile
  Project/backend/codebase/monitoring/router.py
  Project/backend/codebase/monitoring/tests/test_monitoring.py
  Project/backend/codebase/requirements.txt
Labels: enhancement

#73 Feat/cors
  Project/backend/.env.example
  Project/backend/codebase/graph_creator/json_to_graphml.py
  Project/backend/codebase/main.py
  Project/backend/codebase/monitoring/tests/test_monitoring.py
  Project/backend/codebase/tests/test_json_to_graphml.py
  Project/frontend/src/components/Upload/index.tsx
Labels: enhancement

#71 Added gemini and llama3 using API
  Project/backend/.env.example
  Project/backend/codebase/requirements.txt
  Project/backend/config/llm/gemini.py
  Project/backend/config/llm/llama3.py
  Project/backend/config/llm/mistral_docker/Dockerfile
  Project/backend/config/llm/mistral_docker/README.md
  Project/backend/config/llm/mistral_docker/run_ollama.py
Labels: enhancement, Priority - High

#74 Initial graph visualization
  Project/frontend/package-lock.json
  Project/frontend/package.json
  Project/frontend/src/components/App/index.css
  Project/frontend/src/components/App/index.tsx
  Project/frontend/src/components/Graph/index.css
  Project/frontend/src/components/Graph/index.tsx
  Project/frontend/src/components/Home/index.css
  Project/frontend/src/components/Home/index.tsx
  Project/frontend/src/components/Upload/index.tsx
  Project/frontend/src/vite-env.d.ts
Labels: Priority - High
